





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace SitecoreHackathon.Project.Website
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}

namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IHackathons_Landing_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Hackathon Pages/Hackathons Landing Page</para>	
	/// <para>ID: 030ed5c3-d986-4687-8676-8d17f1b34f13</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHackathons_Landing_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHackathons_Landing_Page : IGlassBase , global::SitecoreHackathon.Project.Website.IPage
	{
				}


	public static partial class IHackathons_Landing_PageConstants{

			public const string TemplateIdString = "030ed5c3-d986-4687-8676-8d17f1b34f13";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Hackathons Landing Page";

					
			public static readonly ID ContentFieldId = new ID("d923ef11-3e78-40f1-9eef-4ef07995d719");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID TitleFieldId = new ID("bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Hackathons_Landing_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Hackathon Pages/Hackathons Landing Page</para>	
	/// <para>ID: 030ed5c3-d986-4687-8676-8d17f1b34f13</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHackathons_Landing_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Hackathons_Landing_Page  : GlassBase, IHackathons_Landing_Page 
	{
	   
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: d923ef11-3e78-40f1-9eef-4ef07995d719</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHackathons_Landing_PageConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHackathons_Landing_PageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IPage_Design_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Page Design Folder</para>	
	/// <para>ID: 0f5b5616-5e42-4892-aada-98e1de07b828</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_Design_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage_Design_Folder : IGlassBase 
	{
				}


	public static partial class IPage_Design_FolderConstants{

			public const string TemplateIdString = "0f5b5616-5e42-4892-aada-98e1de07b828";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page Design Folder";

			

	}

	
	/// <summary>
	/// Page_Design_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Page Design Folder</para>	
	/// <para>ID: 0f5b5616-5e42-4892-aada-98e1de07b828</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_Design_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Page_Design_Folder  : GlassBase, IPage_Design_Folder 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IHackathon_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Hackathon Pages/Hackathon Page</para>	
	/// <para>ID: 147b9204-5efc-4ec4-9994-4fa00612b4c1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHackathon_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHackathon_Page : IGlassBase , global::SitecoreHackathon.Project.Website.IPage
	{
								/// <summary>
					/// The Introduction field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: bae0092e-2d0c-46fb-b3c6-522e67159fe7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHackathon_PageConstants.IntroductionFieldName)]
					string Introduction  {get; set;}
			
								/// <summary>
					/// The Year field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 83f79f57-8024-4398-ade6-19c847ffa8ec</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHackathon_PageConstants.YearFieldName)]
					DateTime Year  {get; set;}
			
				}


	public static partial class IHackathon_PageConstants{

			public const string TemplateIdString = "147b9204-5efc-4ec4-9994-4fa00612b4c1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Hackathon Page";

					
			public static readonly ID IntroductionFieldId = new ID("bae0092e-2d0c-46fb-b3c6-522e67159fe7");
			public const string IntroductionFieldName = "Introduction";
			
					
			public static readonly ID YearFieldId = new ID("83f79f57-8024-4398-ade6-19c847ffa8ec");
			public const string YearFieldName = "Year";
			
					
			public static readonly ID ContentFieldId = new ID("d923ef11-3e78-40f1-9eef-4ef07995d719");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID TitleFieldId = new ID("bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Hackathon_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Hackathon Pages/Hackathon Page</para>	
	/// <para>ID: 147b9204-5efc-4ec4-9994-4fa00612b4c1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHackathon_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Hackathon_Page  : GlassBase, IHackathon_Page 
	{
	   
						/// <summary>
				/// The Introduction field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: bae0092e-2d0c-46fb-b3c6-522e67159fe7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHackathon_PageConstants.IntroductionFieldName)]
				public virtual string Introduction  {get; set;}
					
						/// <summary>
				/// The Year field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 83f79f57-8024-4398-ade6-19c847ffa8ec</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHackathon_PageConstants.YearFieldName)]
				public virtual DateTime Year  {get; set;}
					
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: d923ef11-3e78-40f1-9eef-4ef07995d719</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHackathon_PageConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHackathon_PageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IPartial_Design_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Partial Design Folder</para>	
	/// <para>ID: 2e971c56-a2c4-4d11-9f3f-bf0a82db58d3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPartial_Design_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPartial_Design_Folder : IGlassBase 
	{
				}


	public static partial class IPartial_Design_FolderConstants{

			public const string TemplateIdString = "2e971c56-a2c4-4d11-9f3f-bf0a82db58d3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Partial Design Folder";

			

	}

	
	/// <summary>
	/// Partial_Design_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Partial Design Folder</para>	
	/// <para>ID: 2e971c56-a2c4-4d11-9f3f-bf0a82db58d3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPartial_Design_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Partial_Design_Folder  : GlassBase, IPartial_Design_Folder 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IPartial_Design Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Partial Design</para>	
	/// <para>ID: 317a77ff-b497-41c9-9532-de2f9c0ecbc3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPartial_DesignConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPartial_Design : IGlassBase 
	{
				}


	public static partial class IPartial_DesignConstants{

			public const string TemplateIdString = "317a77ff-b497-41c9-9532-de2f9c0ecbc3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Partial Design";

			

	}

	
	/// <summary>
	/// Partial_Design
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Partial Design</para>	
	/// <para>ID: 317a77ff-b497-41c9-9532-de2f9c0ecbc3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPartial_DesignConstants.TemplateIdString)] //, Cachable = true
	public partial class Partial_Design  : GlassBase, IPartial_Design 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// ITenant Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Tenant</para>	
	/// <para>ID: 36b11c69-2ccd-44d9-8186-68ec3fab16e3</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITenantConstants.TemplateIdString )] //, Cachable = true
	public partial interface ITenant : IGlassBase 
	{
				}


	public static partial class ITenantConstants{

			public const string TemplateIdString = "36b11c69-2ccd-44d9-8186-68ec3fab16e3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Tenant";

			

	}

	
	/// <summary>
	/// Tenant
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Tenant</para>	
	/// <para>ID: 36b11c69-2ccd-44d9-8186-68ec3fab16e3</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITenantConstants.TemplateIdString)] //, Cachable = true
	public partial class Tenant  : GlassBase, ITenant 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IPage_Design Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Page Design</para>	
	/// <para>ID: 3d3423b4-aca1-45cd-96d4-fdfa752ab8c3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_DesignConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage_Design : IGlassBase 
	{
				}


	public static partial class IPage_DesignConstants{

			public const string TemplateIdString = "3d3423b4-aca1-45cd-96d4-fdfa752ab8c3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page Design";

			

	}

	
	/// <summary>
	/// Page_Design
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Page Design</para>	
	/// <para>ID: 3d3423b4-aca1-45cd-96d4-fdfa752ab8c3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_DesignConstants.TemplateIdString)] //, Cachable = true
	public partial class Page_Design  : GlassBase, IPage_Design 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Home</para>	
	/// <para>ID: 40cbad69-fc9b-4137-b266-81f4100970a3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome : IGlassBase , global::SitecoreHackathon.Project.Website.IPage
	{
				}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "40cbad69-fc9b-4137-b266-81f4100970a3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

					
			public static readonly ID ContentFieldId = new ID("d923ef11-3e78-40f1-9eef-4ef07995d719");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID TitleFieldId = new ID("bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Home
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Home</para>	
	/// <para>ID: 40cbad69-fc9b-4137-b266-81f4100970a3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString)] //, Cachable = true
	public partial class Home  : GlassBase, IHome 
	{
	   
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: d923ef11-3e78-40f1-9eef-4ef07995d719</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// ISettings Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Settings</para>	
	/// <para>ID: 52aa002e-6015-41f1-8db6-b32330dcac26</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISettingsConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISettings : IGlassBase 
	{
				}


	public static partial class ISettingsConstants{

			public const string TemplateIdString = "52aa002e-6015-41f1-8db6-b32330dcac26";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Settings";

			

	}

	
	/// <summary>
	/// Settings
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Settings</para>	
	/// <para>ID: 52aa002e-6015-41f1-8db6-b32330dcac26</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISettingsConstants.TemplateIdString)] //, Cachable = true
	public partial class Settings  : GlassBase, ISettings 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IPage_Designs Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Page Designs</para>	
	/// <para>ID: 5ce68728-12b7-44a1-9cff-f14d57fb1649</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_DesignsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage_Designs : IGlassBase 
	{
				}


	public static partial class IPage_DesignsConstants{

			public const string TemplateIdString = "5ce68728-12b7-44a1-9cff-f14d57fb1649";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page Designs";

			

	}

	
	/// <summary>
	/// Page_Designs
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Page Designs</para>	
	/// <para>ID: 5ce68728-12b7-44a1-9cff-f14d57fb1649</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_DesignsConstants.TemplateIdString)] //, Cachable = true
	public partial class Page_Designs  : GlassBase, IPage_Designs 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Site</para>	
	/// <para>ID: 6f50b7c2-7006-4216-bf81-c838ed8ac457</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite : IGlassBase 
	{
				}


	public static partial class ISiteConstants{

			public const string TemplateIdString = "6f50b7c2-7006-4216-bf81-c838ed8ac457";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site";

			

	}

	
	/// <summary>
	/// Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Site</para>	
	/// <para>ID: 6f50b7c2-7006-4216-bf81-c838ed8ac457</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString)] //, Cachable = true
	public partial class Site  : GlassBase, ISite 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// ITeams_Landing_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Hackathon Pages/Teams Landing Page</para>	
	/// <para>ID: 852970b3-3534-4661-8540-1a33fe1c0738</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITeams_Landing_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface ITeams_Landing_Page : IGlassBase , global::SitecoreHackathon.Project.Website.IPage
	{
				}


	public static partial class ITeams_Landing_PageConstants{

			public const string TemplateIdString = "852970b3-3534-4661-8540-1a33fe1c0738";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Teams Landing Page";

					
			public static readonly ID ContentFieldId = new ID("d923ef11-3e78-40f1-9eef-4ef07995d719");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID TitleFieldId = new ID("bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Teams_Landing_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Hackathon Pages/Teams Landing Page</para>	
	/// <para>ID: 852970b3-3534-4661-8540-1a33fe1c0738</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITeams_Landing_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Teams_Landing_Page  : GlassBase, ITeams_Landing_Page 
	{
	   
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: d923ef11-3e78-40f1-9eef-4ef07995d719</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITeams_Landing_PageConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITeams_Landing_PageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IPartial_Designs Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Partial Designs</para>	
	/// <para>ID: 879a9452-8f03-4f29-b6f9-f9b828e483b7</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPartial_DesignsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPartial_Designs : IGlassBase 
	{
				}


	public static partial class IPartial_DesignsConstants{

			public const string TemplateIdString = "879a9452-8f03-4f29-b6f9-f9b828e483b7";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Partial Designs";

			

	}

	
	/// <summary>
	/// Partial_Designs
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Partial Designs</para>	
	/// <para>ID: 879a9452-8f03-4f29-b6f9-f9b828e483b7</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPartial_DesignsConstants.TemplateIdString)] //, Cachable = true
	public partial class Partial_Designs  : GlassBase, IPartial_Designs 
	{
	   
			
	}
}
namespace SitecoreHackathon.Project.Website
{


 	/// <summary>
	/// IPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Page</para>	
	/// <para>ID: ccee96cd-19aa-4be3-a548-3b24198aa686</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage : IGlassBase 
	{
								/// <summary>
					/// The Content field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: d923ef11-3e78-40f1-9eef-4ef07995d719</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.ContentFieldName)]
					string Content  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IPageConstants{

			public const string TemplateIdString = "ccee96cd-19aa-4be3-a548-3b24198aa686";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page";

					
			public static readonly ID ContentFieldId = new ID("d923ef11-3e78-40f1-9eef-4ef07995d719");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID TitleFieldId = new ID("bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Alpha Solutions/Habitual Losers/Page</para>	
	/// <para>ID: ccee96cd-19aa-4be3-a548-3b24198aa686</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString)] //, Cachable = true
	public partial class Page  : GlassBase, IPage 
	{
	   
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: d923ef11-3e78-40f1-9eef-4ef07995d719</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: bf1dcf60-d24b-4c4e-87f0-f2e1cc86e12a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
